source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'R87AttributedString_Example', :exclusive => true do
  pod 'R87AttributedString', :path => '../'
end

target 'R87AttributedString_Tests', :exclusive => true do
  pod 'R87AttributedString', :path => '../'

  
end
